name: Deploy to Remote Server my-host.hk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Execute script on remote server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          # Создание директории на удаленном сервере, если ее нет
          mkdir -p /opt/testproj

          # Переход в эту директорию
          cd /opt/testproj

          # Удаление всех файлов и папок в директории (если они существуют)
          rm -rf ./*

          # Клонирование репозитория на удаленный сервер
          git clone https://github.com/${{ github.repository }}

          REPO_NAME=$(basename ${{ github.repository }})
          echo "entering repository:"  $REPO_NAME

          cd $REPO_NAME

          # Создание Docker образа из Dockerfile в репозитории
          docker build --no-cache -t ci-cd-test-ddk:ubuntu-22.04 .

          # Запуск контейнера из только что созданного образа
          docker run --rm ci-cd-test-ddk:ubuntu-22.04
